defaults:
  - train
  - _self_

dataset: rgv49
data_root: /data/fcr/data/rgv_interval_final/raw_data
fixed_frames: 49
split: all
resolution: [518, 392]

fusion: crossattn
event_in_chans: 8
freeze_backbone: True
only_rgb_loss: False
rgb_loss: mse
pretrained_strict: False
rgv_framewise_train: True
rgv_random_num_frames: True
rgv_min_frames: 1
rgv_max_frames: 30
rgv_sample_mode: random
quiet_pil: True
